### ISSUE TITLE
豆瓣链接有7个数字的

### ISSUE THREAD

**Issue by rachpt** [tomorrow505/HUDBT#1]
比如这个：  https://movie.douban.com/subject/1295134/  

建议同时匹配 imdb 链接， wiki 的种子一般不写 豆瓣链接。

https://github.com/tomorrow505/HUDBT/blob/3b0938415e40018515e019b7887c16520e3f2b4b/parser_origin/byr.py#L32

**Comment by tomorrow505** [comment]
嗯嗯，感谢提出意见，已经加进去了。

**Comment by tomorrow505** [comment]
> 比如这个： https://movie.douban.com/subject/1295134/
> 
> 建议同时匹配 imdb 链接， wiki 的种子一般不写 豆瓣链接。
> 
> [HUDBT/parser_origin/byr.py](https://github.com/tomorrow505/HUDBT/blob/3b0938415e40018515e019b7887c16520e3f2b4b/parser_origin/byr.py#L32)
> 
> Line 32 in [3b09384](/tomorrow505/HUDBT/commit/3b0938415e40018515e019b7887c16520e3f2b4b)
> 
>  link = re.search('◎豆瓣链接.*douban.com/subject/(\d{8})', descr)

嗯嗯，已经加进去了
